/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface StoreOptions {
  biEncoder?: string
  crossEncoder?: string
  nClusters?: number
  useRankGap?: boolean
  kShallow?: number
  kDeep?: number
}
export interface Hit {
  id: string
  content: string
  score: number
}
export declare class MemoryStore {
  /**
   * Open or create a store. `options` accepts encoder repo names
   * and tuning knobs; defaults match the Python `MemoryStore`.
   */
  static open(path: string, options?: StoreOptions | undefined | null): Promise<MemoryStore>
  add(content: string): Promise<string | null>
  retrieve(query: string, k?: number | undefined | null): Promise<Array<Hit>>
  save(): Promise<void>
  size(): number
}
